<?php
require_once '../config/session.php';
require_once '../config/db.php';
requireStaffOrAdmin();

$pdo = getConnection();

// Summary by status
$byStatus = $pdo->query(
    "SELECT status, COUNT(*) AS total FROM complaints GROUP BY status ORDER BY total DESC"
)->fetchAll();

// Summary by category
$byCat = $pdo->query(
    "SELECT category, COUNT(*) AS total FROM complaints GROUP BY category ORDER BY total DESC"
)->fetchAll();

// Summary by department
$byDept = $pdo->query(
    "SELECT d.department_name, COUNT(ca.complaint_id) AS total
     FROM departments d
     LEFT JOIN complaint_assignments ca ON d.department_id = ca.department_id
     GROUP BY d.department_id ORDER BY total DESC"
)->fetchAll();

// All resolved complaints
$resolved = $pdo->query(
    "SELECT c.complaint_id, c.category, c.location, u.name AS citizen, c.date_submitted
     FROM complaints c JOIN users u ON c.user_id = u.user_id
     WHERE c.status = 'Resolved'
     ORDER BY c.date_submitted DESC"
)->fetchAll();

// Total complaints
$totalComplaints = $pdo->query("SELECT COUNT(*) FROM complaints")->fetchColumn();
$generatedAt = date('d M Y, h:i A');
?>
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Municipality Complaint Report - <?= $generatedAt ?></title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: Arial, sans-serif; font-size: 13px; color: #222; background: #fff; padding: 30px; }

    .header { text-align: center; border-bottom: 3px solid #1a73e8; padding-bottom: 16px; margin-bottom: 24px; }
    .header h1 { font-size: 22px; color: #1a73e8; margin-bottom: 4px; }
    .header p { font-size: 12px; color: #666; }

    .meta { display: flex; justify-content: space-between; margin-bottom: 24px; font-size: 12px; color: #555; }

    .section-title { font-size: 14px; font-weight: bold; color: #1a73e8; border-left: 4px solid #1a73e8; padding-left: 8px; margin-bottom: 10px; margin-top: 24px; }

    .stats-grid { display: grid; grid-template-columns: repeat(4, 1fr); gap: 12px; margin-bottom: 24px; }
    .stat-box { border: 1px solid #ddd; border-radius: 6px; padding: 12px; text-align: center; }
    .stat-box .val { font-size: 26px; font-weight: bold; color: #1a73e8; }
    .stat-box .lbl { font-size: 11px; color: #666; margin-top: 2px; }

    .tables-row { display: grid; grid-template-columns: repeat(3, 1fr); gap: 16px; margin-bottom: 24px; }

    table { width: 100%; border-collapse: collapse; font-size: 12px; }
    thead tr { background: #1a73e8; color: #fff; }
    thead th { padding: 7px 10px; text-align: left; }
    tbody tr:nth-child(even) { background: #f5f8ff; }
    tbody td { padding: 6px 10px; border-bottom: 1px solid #eee; }

    .badge { display: inline-block; padding: 2px 8px; border-radius: 10px; font-size: 11px; font-weight: bold; color: #fff; }
    .badge-warning  { background: #fd7e14; }
    .badge-info     { background: #0dcaf0; color: #000; }
    .badge-success  { background: #198754; }
    .badge-danger   { background: #dc3545; }

    .footer { margin-top: 32px; border-top: 1px solid #ddd; padding-top: 10px; text-align: center; font-size: 11px; color: #aaa; }

    @media print {
      body { padding: 15px; }
      .no-print { display: none !important; }
      @page { margin: 1cm; }
    }

    .print-btn {
      position: fixed; top: 20px; right: 20px;
      background: #1a73e8; color: #fff; border: none;
      padding: 10px 20px; border-radius: 6px; font-size: 13px;
      cursor: pointer; display: flex; align-items: center; gap: 6px;
      box-shadow: 0 2px 8px rgba(0,0,0,0.2);
    }
    .print-btn:hover { background: #1558b0; }
  </style>
</head>
<body>

  <!-- Print Button (hidden when printing) -->
  <button class="print-btn no-print" onclick="window.print()">
    🖨️ Print / Save as PDF
  </button>

  <!-- Header -->
  <div class="header">
    <h1>🏛️ Municipality Complaint Tracking System</h1>
    <p>Official Complaints Report</p>
  </div>

  <!-- Meta -->
  <div class="meta">
    <span><strong>Generated by:</strong> <?= htmlspecialchars($_SESSION['name']) ?> (<?= ucfirst($_SESSION['role']) ?>)</span>
    <span><strong>Generated on:</strong> <?= $generatedAt ?></span>
  </div>

  <!-- Summary Stats -->
  <div class="section-title">Summary</div>
  <?php
    $statusMap = [];
    foreach ($byStatus as $s) $statusMap[$s['status']] = $s['total'];
  ?>
  <div class="stats-grid">
    <div class="stat-box">
      <div class="val"><?= $totalComplaints ?></div>
      <div class="lbl">Total Complaints</div>
    </div>
    <div class="stat-box">
      <div class="val" style="color:#fd7e14"><?= $statusMap['Pending'] ?? 0 ?></div>
      <div class="lbl">Pending</div>
    </div>
    <div class="stat-box">
      <div class="val" style="color:#0dcaf0"><?= $statusMap['In Progress'] ?? 0 ?></div>
      <div class="lbl">In Progress</div>
    </div>
    <div class="stat-box">
      <div class="val" style="color:#198754"><?= $statusMap['Resolved'] ?? 0 ?></div>
      <div class="lbl">Resolved</div>
    </div>
  </div>

  <!-- Three tables side by side -->
  <div class="section-title">Breakdown</div>
  <div class="tables-row">

    <!-- By Status -->
    <div>
      <table>
        <thead><tr><th>Status</th><th>Count</th></tr></thead>
        <tbody>
        <?php $badgeMap = ['Pending'=>'warning','In Progress'=>'info','Resolved'=>'success','Rejected'=>'danger']; ?>
        <?php foreach ($byStatus as $r): ?>
        <tr>
          <td><span class="badge badge-<?= $badgeMap[$r['status']] ?? 'secondary' ?>"><?= $r['status'] ?></span></td>
          <td><?= $r['total'] ?></td>
        </tr>
        <?php endforeach; ?>
        <?php if (!$byStatus): ?><tr><td colspan="2" style="text-align:center;color:#aaa">No data</td></tr><?php endif; ?>
        </tbody>
      </table>
    </div>

    <!-- By Category -->
    <div>
      <table>
        <thead><tr><th>Category</th><th>Count</th></tr></thead>
        <tbody>
        <?php foreach ($byCat as $r): ?>
        <tr><td><?= htmlspecialchars($r['category']) ?></td><td><?= $r['total'] ?></td></tr>
        <?php endforeach; ?>
        <?php if (!$byCat): ?><tr><td colspan="2" style="text-align:center;color:#aaa">No data</td></tr><?php endif; ?>
        </tbody>
      </table>
    </div>

    <!-- By Department -->
    <div>
      <table>
        <thead><tr><th>Department</th><th>Assigned</th></tr></thead>
        <tbody>
        <?php foreach ($byDept as $r): ?>
        <tr><td><?= htmlspecialchars($r['department_name']) ?></td><td><?= $r['total'] ?></td></tr>
        <?php endforeach; ?>
        <?php if (!$byDept): ?><tr><td colspan="2" style="text-align:center;color:#aaa">No data</td></tr><?php endif; ?>
        </tbody>
      </table>
    </div>

  </div>

  <!-- Resolved Complaints -->
  <div class="section-title">Resolved Complaints</div>
  <table>
    <thead>
      <tr><th>#ID</th><th>Category</th><th>Location</th><th>Citizen</th><th>Date</th></tr>
    </thead>
    <tbody>
    <?php foreach ($resolved as $r): ?>
    <tr>
      <td>#<?= $r['complaint_id'] ?></td>
      <td><?= htmlspecialchars($r['category']) ?></td>
      <td><?= htmlspecialchars($r['location']) ?></td>
      <td><?= htmlspecialchars($r['citizen']) ?></td>
      <td><?= date('d M Y', strtotime($r['date_submitted'])) ?></td>
    </tr>
    <?php endforeach; ?>
    <?php if (!$resolved): ?>
    <tr><td colspan="5" style="text-align:center;color:#aaa;padding:12px">No resolved complaints yet.</td></tr>
    <?php endif; ?>
    </tbody>
  </table>

  <div class="footer">
    Municipality Complaint Tracking System &mdash; Confidential Report &mdash; <?= $generatedAt ?>
  </div>

  <script>
    // Auto-trigger print dialog on load (optional — comment out if not desired)
    // window.onload = () => window.print();
  </script>

</body>
</html>
